services:
  - type: worker
    name: telegram-love-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production